### ISSUE TITLE
Grammar: Complete writing grammar in ENBF

### ISSUE THREAD

**Issue by nouritsu** [nouritsu/rs-pseudocode#3]
The repository has a [grammar/grammar.enbf](https://github.com/nouritsu/rs-pseudocode/blob/main/grammar/grammar.ebnf) that defines grammar rules to be implemented using chumsky.

[This](https://github.com/nouritsu/rs-pseudocode/blob/main/grammar/ENBF_ref.ebnf) can be used to understand ENBF syntax and [this](https://github.com/nouritsu/rs-pseudocode/blob/main/grammar/Pseudocode_Ref.pdf) can be used to understand Pseudocode syntax.

**Comment by monofe** [comment]
I'll take it up

**Comment by nouritsu** [comment]
Accidental close.

**Comment by nouritsu** [comment]
Closing as this project has been abandoned
